In [48]:
import pandas as pd
import numpy as nm

In [49]:
df=pd.DataFrame({
       'OrderID' : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],

'CustomerID' : ["C001","C002","C003","C004","C005","C006","C007","C008","C009","C010","C011","C012","C013","C014","C015","C016","C017","C018","C019","C020","C021","C022","C023","C024","C025"],

'Product':  ["Smartphone","Laptop","Wireless Mouse","Bluetooth Speaker","Headphones","Smartwatch","Tablet","USB Cable","Power Bank","Keyboard","Office Chair","Study Table","Running Shoes","Jeans","T-Shirt","Pressure Cooker","Electric Kettle","Mixer Grinder","Water Bottle","Air Fryer","Notebook","Pen","Marker","Diary","Calculator"],

'Category':  ["Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Furniture","Furniture","Fashion","Fashion","Fashion","Home Appliances","Home Appliances","Home Appliances","Home Appliances","Home Appliances","Stationery","Stationery","Stationery","Stationery","Stationery"],

'Quantity' :[1,1,2,1,1,1,2,3,1,1,1,1,2,2,3,1,1,1,2,1,5,10,4,2,1],

'Price' :  [18000,55000,800,2500,3000,12000,22000,300,1500,1200,7000,8500,3500,2200,600,3000,1800,5000,400,9000,100,20,50,300,800],

'OrderDate':  ["2023-01-15","2023-02-10","2023-03-05","2023-04-18","2023-05-12","2023-06-25","2023-07-19","2023-08-02","2023-09-14","2023-10-30","2023-11-05","2023-12-22","2024-01-08","2024-01-20","2024-02-14","2024-02-28","2024-03-10","2024-03-25","2024-04-05","2024-04-18","2024-05-02","2024-05-15","2024-05-28","2024-06-10","2024-06-25"],

'Rating'  :[5,5,4,4,3,5,4,3,4,4,5,4,4,3,3,5,4,4,3,5,3,2,3,4,5],

'Review' : ["Excellent phone with great performance","Laptop is fast and reliable","Mouse works smoothly","Speaker has powerful sound","Average headphone quality","Very useful smartwatch","Tablet is perfect for study","Cable quality is decent","Power bank charges fast","Keyboard is comfortable","Chair is very comfortable","Table has strong build","Shoes are comfortable for running","Jeans fabric is good","T shirt quality is average","Cooker works perfectly","Kettle heats water fast","Mixer is powerful","Bottle is leak proof","Air fryer is amazing","Notebook pages are smooth","Pen ink flow is poor","Marker color is bright","Diary looks premium","Calculator is accurate"],

})
df

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5,Excellent phone with great performance
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5,Laptop is fast and reliable
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4,Mouse works smoothly
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4,Speaker has powerful sound
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3,Average headphone quality
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5,Very useful smartwatch
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4,Tablet is perfect for study
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3,Cable quality is decent
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4,Power bank charges fast
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4,Keyboard is comfortable
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5,Chair is very comfortable
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4,Table has strong build
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4,Shoes are comfortable for running
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3,Jeans fabric is good
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3,T shirt quality is average
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5,Cooker works perfectly
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4,Kettle heats water fast
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4,Mixer is powerful
18,19,C019,Water Bottle,Home Appliances,2,400,2024-04-05,3,Bottle is leak proof
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5,Air fryer is amazing
20,21,C021,Notebook,Stationery,5,100,2024-05-02,3,Notebook pages are smooth
21,22,C022,Pen,Stationery,10,20,2024-05-15,2,Pen ink flow is poor
22,23,C023,Marker,Stationery,4,50,2024-05-28,3,Marker color is bright
23,24,C024,Diary,Stationery,2,300,2024-06-10,4,Diary looks premium
24,25,C025,Calculator,Stationery,1,800,2024-06-25,5,Calculator is accurate

In [50]:
print("top 10 records")
df.head(10)

top 10 records

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5,Excellent phone with great performance
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5,Laptop is fast and reliable
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4,Mouse works smoothly
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4,Speaker has powerful sound
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3,Average headphone quality
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5,Very useful smartwatch
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4,Tablet is perfect for study
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3,Cable quality is decent
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4,Power bank charges fast
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4,Keyboard is comfortable

In [51]:
print("last 5 records")
df.head(5)

last 5 records

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5,Excellent phone with great performance
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5,Laptop is fast and reliable
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4,Mouse works smoothly
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4,Speaker has powerful sound
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3,Average headphone quality

In [52]:
# Q2: Use info() and describe() to get a comprehensive overview of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     25 non-null     int64
 1   CustomerID  25 non-null     object
 2   Product     25 non-null     object
 3   Category    25 non-null     object
 4   Quantity    25 non-null     int64
 5   Price       25 non-null     int64
 6   OrderDate   25 non-null     object
 7   Rating      25 non-null     int64
 8   Review      25 non-null     object
dtypes: int64(4), object(5)
memory usage: 1.9+ KB

In [53]:
df.describe()

         OrderID   Quantity         Price     Rating
count  25.000000  25.000000     25.000000  25.000000
mean   13.000000   2.040000   6342.800000   3.920000
std     7.359801   1.968079  11634.601956   0.862168
min     1.000000   1.000000     20.000000   2.000000
25%     7.000000   1.000000    600.000000   3.000000
50%    13.000000   1.000000   2200.000000   4.000000
75%    19.000000   2.000000   7000.000000   5.000000
max    25.000000  10.000000  55000.000000   5.000000

In [54]:
# Identify data types, missing values, and statistical summary
print("data types : \n",df.dtypes)

data types :
 OrderID        int64
CustomerID    object
Product       object
Category      object
Quantity       int64
Price          int64
OrderDate     object
Rating         int64
Review        object
dtype: object

In [55]:
print("missing values : \n",df.isna())

missing values :
     OrderID  CustomerID  Product  Category  Quantity  Price  OrderDate  \
0     False       False    False     False     False  False      False
1     False       False    False     False     False  False      False
2     False       False    False     False     False  False      False
3     False       False    False     False     False  False      False
4     False       False    False     False     False  False      False
5     False       False    False     False     False  False      False
6     False       False    False     False     False  False      False
7     False       False    False     False     False  False      False
8     False       False    False     False     False  False      False
9     False       False    False     False     False  False      False
10    False       False    False     False     False  False      False
11    False       False    False     False     False  False      False
12    False       False    False     False     False  False      False
13    False       False    False     False     False  False      False
14    False       False    False     False     False  False      False
15    False       False    False     False     False  False      False
16    False       False    False     False     False  False      False
17    False       False    False     False     False  False      False
18    False       False    False     False     False  False      False
19    False       False    False     False     False  False      False
20    False       False    False     False     False  False      False
21    False       False    False     False     False  False      False
22    False       False    False     False     False  False      False
23    False       False    False     False     False  False      False
24    False       False    False     False     False  False      False

    Rating  Review
0    False   False
1    False   False
2    False   False
3    False   False
4    False   False
5    False   False
6    False   False
7    False   False
8    False   False
9    False   False
10   False   False
11   False   False
12   False   False
13   False   False
14   False   False
15   False   False
16   False   False
17   False   False
18   False   False
19   False   False
20   False   False
21   False   False
22   False   False
23   False   False
24   False   False

In [56]:
# Print the column names using columns attribute and shape of the dataset
print('column names')
df.columns

column names

Index(['OrderID', 'CustomerID', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Rating', 'Review'],
      dtype='object')

In [57]:
print("shape :")
df.shape

shape :

(25, 9)

In [58]:
# Q3: Introduce 10% missing values randomly in Rating and Review columns
import random
for i in range(1,4):
    x=random.randint(0,24)
    df.loc[x,'Rating']=None
for i in range(1,4):
    x=random.randint(0,24)
    df.loc[x,'Review']=None

In [59]:
df.isna().sum()

OrderID       0
CustomerID    0
Product       0
Category      0
Quantity      0
Price         0
OrderDate     0
Rating        3
Review        2
dtype: int64

In [69]:
df['Rating'].fillna(df['Rating'].median(),inplace=True)

C:\Users\91876\AppData\Local\Temp\ipykernel_15232\822450396.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].median(),inplace=True)

In [70]:
df['Rating'].isna().sum()

0

In [71]:
df['Review'].fillna("NO Review provided",inplace=True)

C:\Users\91876\AppData\Local\Temp\ipykernel_15232\2466105816.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review'].fillna("NO Review provided",inplace=True)

In [72]:
df['Review'].isna().sum()

0

In [73]:
# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price
df['TotalAmount']=df['Quantity']*df['Price']
df

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5.0,Excellent phone with great performance,18000
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5.0,Laptop is fast and reliable,55000
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4.0,NO Review provided,1600
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4.0,Speaker has powerful sound,2500
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3.0,NO Review provided,3000
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5.0,Very useful smartwatch,12000
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4.0,Tablet is perfect for study,44000
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3.0,Cable quality is decent,900
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4.0,Power bank charges fast,1500
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4.0,Keyboard is comfortable,1200
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5.0,Chair is very comfortable,7000
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4.0,Table has strong build,8500
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4.0,Shoes are comfortable for running,7000
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3.0,Jeans fabric is good,4400
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3.0,T shirt quality is average,1800
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5.0,Cooker works perfectly,3000
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4.0,Kettle heats water fast,1800
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4.0,Mixer is powerful,5000
18,19,C019,Water Bottle,Home Appliances,2,400,2024-04-05,3.0,Bottle is leak proof,800
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5.0,Air fryer is amazing,9000
20,21,C021,Notebook,Stationery,5,100,2024-05-02,3.0,Notebook pages are smooth,500
21,22,C022,Pen,Stationery,10,20,2024-05-15,2.0,Pen ink flow is poor,200
22,23,C023,Marker,Stationery,4,50,2024-05-28,3.0,Marker color is bright,200
23,24,C024,Diary,Stationery,2,300,2024-06-10,4.0,Diary looks premium,600
24,25,C025,Calculator,Stationery,1,800,2024-06-25,5.0,Calculator is accurate,800

In [74]:
# Add another column 'DiscountedPrice' that applies 10% discount on orders above $100
df['DiscountedPrice'] = df['TotalAmount'].apply(lambda x: x * 0.1 if x > 1500 else x)
df

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount,DiscountedPrice
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5.0,Excellent phone with great performance,18000,1800.0
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5.0,Laptop is fast and reliable,55000,5500.0
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4.0,NO Review provided,1600,160.0
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4.0,Speaker has powerful sound,2500,250.0
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3.0,NO Review provided,3000,300.0
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5.0,Very useful smartwatch,12000,1200.0
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4.0,Tablet is perfect for study,44000,4400.0
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3.0,Cable quality is decent,900,900.0
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4.0,Power bank charges fast,1500,1500.0
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4.0,Keyboard is comfortable,1200,1200.0
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5.0,Chair is very comfortable,7000,700.0
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4.0,Table has strong build,8500,850.0
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4.0,Shoes are comfortable for running,7000,700.0
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3.0,Jeans fabric is good,4400,440.0
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3.0,T shirt quality is average,1800,180.0
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5.0,Cooker works perfectly,3000,300.0
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4.0,Kettle heats water fast,1800,180.0
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4.0,Mixer is powerful,5000,500.0
18,19,C019,Water Bottle,Home Appliances,2,400,2024-04-05,3.0,Bottle is leak proof,800,800.0
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5.0,Air fryer is amazing,9000,900.0
20,21,C021,Notebook,Stationery,5,100,2024-05-02,3.0,Notebook pages are smooth,500,500.0
21,22,C022,Pen,Stationery,10,20,2024-05-15,2.0,Pen ink flow is poor,200,200.0
22,23,C023,Marker,Stationery,4,50,2024-05-28,3.0,Marker color is bright,200,200.0
23,24,C024,Diary,Stationery,2,300,2024-06-10,4.0,Diary looks premium,600,600.0
24,25,C025,Calculator,Stationery,1,800,2024-06-25,5.0,Calculator is accurate,800,800.0

In [77]:
filtered_df = df[df['TotalAmount'] > 1500]
print("records above 1500 ")
filtered_df

records above 1500

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount,DiscountedPrice
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5.0,Excellent phone with great performance,18000,1800.0
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5.0,Laptop is fast and reliable,55000,5500.0
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4.0,NO Review provided,1600,160.0
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4.0,Speaker has powerful sound,2500,250.0
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3.0,NO Review provided,3000,300.0
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5.0,Very useful smartwatch,12000,1200.0
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4.0,Tablet is perfect for study,44000,4400.0
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5.0,Chair is very comfortable,7000,700.0
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4.0,Table has strong build,8500,850.0
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4.0,Shoes are comfortable for running,7000,700.0
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3.0,Jeans fabric is good,4400,440.0
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3.0,T shirt quality is average,1800,180.0
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5.0,Cooker works perfectly,3000,300.0
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4.0,Kettle heats water fast,1800,180.0
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4.0,Mixer is powerful,5000,500.0
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5.0,Air fryer is amazing,9000,900.0

In [78]:
# Q5: Select only the columns: Product, Category, TotalAmount, and Rating
df2=df[['Product','Category','TotalAmount','Rating']]
df2

              Product         Category  TotalAmount  Rating
0          Smartphone      Electronics        18000     5.0
1              Laptop      Electronics        55000     5.0
2      Wireless Mouse      Electronics         1600     4.0
3   Bluetooth Speaker      Electronics         2500     4.0
4          Headphones      Electronics         3000     3.0
5          Smartwatch      Electronics        12000     5.0
6              Tablet      Electronics        44000     4.0
7           USB Cable      Electronics          900     3.0
8          Power Bank      Electronics         1500     4.0
9            Keyboard      Electronics         1200     4.0
10       Office Chair        Furniture         7000     5.0
11        Study Table        Furniture         8500     4.0
12      Running Shoes          Fashion         7000     4.0
13              Jeans          Fashion         4400     3.0
14            T-Shirt          Fashion         1800     3.0
15    Pressure Cooker  Home Appliances         3000     5.0
16    Electric Kettle  Home Appliances         1800     4.0
17      Mixer Grinder  Home Appliances         5000     4.0
18       Water Bottle  Home Appliances          800     3.0
19          Air Fryer  Home Appliances         9000     5.0
20           Notebook       Stationery          500     3.0
21                Pen       Stationery          200     2.0
22             Marker       Stationery          200     3.0
23              Diary       Stationery          600     4.0
24         Calculator       Stationery          800     5.0

In [86]:
# Filter and display all orders from the 'Electronics' category with Rating >= 4
s3=df2[(df2['Category']=='Electronics') & (df['Rating']>=4)]
s3

             Product     Category  TotalAmount  Rating
0         Smartphone  Electronics        18000     5.0
1             Laptop  Electronics        55000     5.0
2     Wireless Mouse  Electronics         1600     4.0
3  Bluetooth Speaker  Electronics         2500     4.0
5         Smartwatch  Electronics        12000     5.0
6             Tablet  Electronics        44000     4.0
8         Power Bank  Electronics         1500     4.0
9           Keyboard  Electronics         1200     4.0

In [89]:
# Q6: Use boolean indexing to find all orders where:
# - Quantity > 2 AND Price < 50 OR Rating == 5
s4=df[(df['Quantity'] > 2) & ((df['Price'] < 100) | (df['Rating'] == 5))]
s4

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount,DiscountedPrice
21,22,C022,Pen,Stationery,10,20,2024-05-15,2.0,Pen ink flow is poor,200,200.0
22,23,C023,Marker,Stationery,4,50,2024-05-28,3.0,Marker color is bright,200,200.0

In [92]:
# Display the count of such orders
print("count : ",len(s4))

count :  2

In [96]:
# Q7: Sort the entire DataFrame by OrderDate (descending)
#and then by TotalAmount (descending)
s5=df.sort_values(by='OrderDate',ascending=False)
s5

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount,DiscountedPrice
24,25,C025,Calculator,Stationery,1,800,2024-06-25,5.0,Calculator is accurate,800,800.0
23,24,C024,Diary,Stationery,2,300,2024-06-10,4.0,Diary looks premium,600,600.0
22,23,C023,Marker,Stationery,4,50,2024-05-28,3.0,Marker color is bright,200,200.0
21,22,C022,Pen,Stationery,10,20,2024-05-15,2.0,Pen ink flow is poor,200,200.0
20,21,C021,Notebook,Stationery,5,100,2024-05-02,3.0,Notebook pages are smooth,500,500.0
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5.0,Air fryer is amazing,9000,900.0
18,19,C019,Water Bottle,Home Appliances,2,400,2024-04-05,3.0,Bottle is leak proof,800,800.0
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4.0,Mixer is powerful,5000,500.0
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4.0,Kettle heats water fast,1800,180.0
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5.0,Cooker works perfectly,3000,300.0
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3.0,T shirt quality is average,1800,180.0
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3.0,Jeans fabric is good,4400,440.0
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4.0,Shoes are comfortable for running,7000,700.0
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4.0,Table has strong build,8500,850.0
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5.0,Chair is very comfortable,7000,700.0
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4.0,Keyboard is comfortable,1200,1200.0
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4.0,Power bank charges fast,1500,1500.0
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3.0,Cable quality is decent,900,900.0
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4.0,Tablet is perfect for study,44000,4400.0
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5.0,Very useful smartwatch,12000,1200.0
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3.0,NO Review provided,3000,300.0
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4.0,Speaker has powerful sound,2500,250.0
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4.0,NO Review provided,1600,160.0
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5.0,Laptop is fast and reliable,55000,5500.0
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5.0,Excellent phone with great performance,18000,1800.0

In [97]:
s6=df.sort_values(by='TotalAmount',ascending=False)
s6

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount,DiscountedPrice
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5.0,Laptop is fast and reliable,55000,5500.0
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4.0,Tablet is perfect for study,44000,4400.0
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5.0,Excellent phone with great performance,18000,1800.0
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5.0,Very useful smartwatch,12000,1200.0
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5.0,Air fryer is amazing,9000,900.0
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4.0,Table has strong build,8500,850.0
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5.0,Chair is very comfortable,7000,700.0
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4.0,Shoes are comfortable for running,7000,700.0
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4.0,Mixer is powerful,5000,500.0
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3.0,Jeans fabric is good,4400,440.0
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3.0,NO Review provided,3000,300.0
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5.0,Cooker works perfectly,3000,300.0
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4.0,Speaker has powerful sound,2500,250.0
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4.0,Kettle heats water fast,1800,180.0
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3.0,T shirt quality is average,1800,180.0
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4.0,NO Review provided,1600,160.0
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4.0,Power bank charges fast,1500,1500.0
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4.0,Keyboard is comfortable,1200,1200.0
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3.0,Cable quality is decent,900,900.0
18,19,C019,Water Bottle,Home Appliances,2,400,2024-04-05,3.0,Bottle is leak proof,800,800.0
24,25,C025,Calculator,Stationery,1,800,2024-06-25,5.0,Calculator is accurate,800,800.0
23,24,C024,Diary,Stationery,2,300,2024-06-10,4.0,Diary looks premium,600,600.0
20,21,C021,Notebook,Stationery,5,100,2024-05-02,3.0,Notebook pages are smooth,500,500.0
21,22,C022,Pen,Stationery,10,20,2024-05-15,2.0,Pen ink flow is poor,200,200.0
22,23,C023,Marker,Stationery,4,50,2024-05-28,3.0,Marker color is bright,200,200.0

In [98]:
# Create a new column 'SalesRank' that ranks products by TotalAmount 
# in descending order
df['SalesRank'] = df['TotalAmount'].rank(ascending=False)
df

,OrderID,CustomerID,Product,Category,Quantity,Price,OrderDate,Rating,Review,TotalAmount,DiscountedPrice,SalesRank
0,1,C001,Smartphone,Electronics,1,18000,2023-01-15,5.0,Excellent phone with great performance,18000,1800.0,3.0
1,2,C002,Laptop,Electronics,1,55000,2023-02-10,5.0,Laptop is fast and reliable,55000,5500.0,1.0
2,3,C003,Wireless Mouse,Electronics,2,800,2023-03-05,4.0,NO Review provided,1600,160.0,16.0
3,4,C004,Bluetooth Speaker,Electronics,1,2500,2023-04-18,4.0,Speaker has powerful sound,2500,250.0,13.0
4,5,C005,Headphones,Electronics,1,3000,2023-05-12,3.0,NO Review provided,3000,300.0,11.5
5,6,C006,Smartwatch,Electronics,1,12000,2023-06-25,5.0,Very useful smartwatch,12000,1200.0,4.0
6,7,C007,Tablet,Electronics,2,22000,2023-07-19,4.0,Tablet is perfect for study,44000,4400.0,2.0
7,8,C008,USB Cable,Electronics,3,300,2023-08-02,3.0,Cable quality is decent,900,900.0,19.0
8,9,C009,Power Bank,Electronics,1,1500,2023-09-14,4.0,Power bank charges fast,1500,1500.0,17.0
9,10,C010,Keyboard,Electronics,1,1200,2023-10-30,4.0,Keyboard is comfortable,1200,1200.0,18.0
10,11,C011,Office Chair,Furniture,1,7000,2023-11-05,5.0,Chair is very comfortable,7000,700.0,7.5
11,12,C012,Study Table,Furniture,1,8500,2023-12-22,4.0,Table has strong build,8500,850.0,6.0
12,13,C013,Running Shoes,Fashion,2,3500,2024-01-08,4.0,Shoes are comfortable for running,7000,700.0,7.5
13,14,C014,Jeans,Fashion,2,2200,2024-01-20,3.0,Jeans fabric is good,4400,440.0,10.0
14,15,C015,T-Shirt,Fashion,3,600,2024-02-14,3.0,T shirt quality is average,1800,180.0,14.5
15,16,C016,Pressure Cooker,Home Appliances,1,3000,2024-02-28,5.0,Cooker works perfectly,3000,300.0,11.5
16,17,C017,Electric Kettle,Home Appliances,1,1800,2024-03-10,4.0,Kettle heats water fast,1800,180.0,14.5
17,18,C018,Mixer Grinder,Home Appliances,1,5000,2024-03-25,4.0,Mixer is powerful,5000,500.0,9.0
18,19,C019,Water Bottle,Home Appliances,2,400,2024-04-05,3.0,Bottle is leak proof,800,800.0,20.5
19,20,C020,Air Fryer,Home Appliances,1,9000,2024-04-18,5.0,Air fryer is amazing,9000,900.0,5.0
20,21,C021,Notebook,Stationery,5,100,2024-05-02,3.0,Notebook pages are smooth,500,500.0,23.0
21,22,C022,Pen,Stationery,10,20,2024-05-15,2.0,Pen ink flow is poor,200,200.0,24.5
22,23,C023,Marker,Stationery,4,50,2024-05-28,3.0,Marker color is bright,200,200.0,24.5
23,24,C024,Diary,Stationery,2,300,2024-06-10,4.0,Diary looks premium,600,600.0,22.0
24,25,C025,Calculator,Stationery,1,800,2024-06-25,5.0,Calculator is accurate,800,800.0,20.5

In [99]:
# Q8: Find the top 5 best-selling products based on total quantity sold
s7= df.groupby('Product')['Quantity'].sum()

In [100]:
s7=s7.sort_values(ascending=False)

In [101]:
print("top 5 products based on quantity")
s7.head(5)

top 5 products based on quantity

Product
Pen          10
Notebook      5
Marker        4
USB Cable     3
T-Shirt       3
Name: Quantity, dtype: int64

In [102]:
print("products and their quantity in descending order")
s7

products and their quantity in descending order

Product
Pen                  10
Notebook              5
Marker                4
USB Cable             3
T-Shirt               3
Wireless Mouse        2
Water Bottle          2
Diary                 2
Tablet                2
Jeans                 2
Running Shoes         2
Pressure Cooker       1
Study Table           1
Smartwatch            1
Smartphone            1
Air Fryer             1
Power Bank            1
Bluetooth Speaker     1
Mixer Grinder         1
Laptop                1
Keyboard              1
Headphones            1
Electric Kettle       1
Calculator            1
Office Chair          1
Name: Quantity, dtype: int64

In [109]:
# Q9: Group the data by 'Category' and calculate:
# - Total sales (sum of TotalAmount)
# - Average rating
# - Number of orders
# Display the results sorted by total sales
s9 = df.groupby('Category').agg(TotalSales=('TotalAmount', 'sum'),AvgRating=('Rating', 'mean'),NumOrders=('OrderID', 'count')).sort_values(by='TotalSales', ascending=False)
s9

                 TotalSales  AvgRating  NumOrders
Category
Electronics          139700   4.100000         10
Home Appliances       19600   4.200000          5
Furniture             15500   4.500000          2
Fashion               13200   3.333333          3
Stationery             2300   3.400000          5

In [ ]:
# Q10: Create a pivot table showing average Price for each Category and
#Rating combination

In [112]:
# Q11: Convert the Quantity and Price columns to NumPy arrays
q=nm.array(df['Quantity'])
p=nm.array(df['Price'])
print("quantity array",q)
print("price array",p)

quantity array [ 1  1  2  1  1  1  2  3  1  1  1  1  2  2  3  1  1  1  2  1  5 10  4  2
  1]
price array [18000 55000   800  2500  3000 12000 22000   300  1500  1200  7000  8500
  3500  2200   600  3000  1800  5000   400  9000   100    20    50   300
   800]

In [116]:
l1=list(q)
l2=list(p)
l3=list(zip(l1,l2))
l3

[(1, 18000),
 (1, 55000),
 (2, 800),
 (1, 2500),
 (1, 3000),
 (1, 12000),
 (2, 22000),
 (3, 300),
 (1, 1500),
 (1, 1200),
 (1, 7000),
 (1, 8500),
 (2, 3500),
 (2, 2200),
 (3, 600),
 (1, 3000),
 (1, 1800),
 (1, 5000),
 (2, 400),
 (1, 9000),
 (5, 100),
 (10, 20),
 (4, 50),
 (2, 300),
 (1, 800)]

In [117]:
arr=nm.array(l3)
arr

array([[    1, 18000],
       [    1, 55000],
       [    2,   800],
       [    1,  2500],
       [    1,  3000],
       [    1, 12000],
       [    2, 22000],
       [    3,   300],
       [    1,  1500],
       [    1,  1200],
       [    1,  7000],
       [    1,  8500],
       [    2,  3500],
       [    2,  2200],
       [    3,   600],
       [    1,  3000],
       [    1,  1800],
       [    1,  5000],
       [    2,   400],
       [    1,  9000],
       [    5,   100],
       [   10,    20],
       [    4,    50],
       [    2,   300],
       [    1,   800]], dtype=int64)

In [121]:
# Display array properties: shape, dtype, ndim, size
print("shape :",arr.shape)
print("data type :",arr.dtype)
print("dimensions :",arr.ndim)
print("size :",arr.size)

shape : (25, 2)
data type : int64
dimensions : 2
size : 50

In [123]:
# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500
prices = nm.random.randint(10, 501, size=100) 
prices

array([257, 363,  31, 361, 411, 270, 173, 307, 290, 477, 119, 139, 352,
       398,  21,  67, 351, 329, 166, 374, 321, 375, 357, 386, 383, 260,
       224,  49, 439, 329, 473, 271, 241, 256, 385, 146,  40,  52, 113,
       343, 277, 451,  80, 362, 464, 302, 305, 258, 423, 418,  30, 350,
        82, 290, 405, 377, 380, 314, 159, 299, 147, 379, 254, 321,  32,
       446, 490, 174, 468, 130, 248, 199, 403, 172, 421, 359, 450, 462,
       461, 160, 143, 126, 141, 367, 384,  38, 109,  93, 167,  73,  47,
        49, 222, 259, 443, 153, 471,  21, 187,  69])

In [125]:
# Calculate mean, median, standard deviation, min, and max using NumPy functions
m1 = nm.mean(prices)
m2 = nm.median(prices)
m3 = nm.std(prices)
m4 = nm.min(prices)
m5 = nm.max(prices)

print("Mean:", m1)
print("Median:", m2)
print("Std Dev:", m3)
print("Min:", m4)
print("Max:", m5)

Mean: 264.63
Median: 283.5
Std Dev: 139.2946269602672
Min: 21
Max: 490

In [126]:
# Reshape this array into a 10x10 matrix
mat = prices.reshape(10, 10)
mat

array([[257, 363,  31, 361, 411, 270, 173, 307, 290, 477],
       [119, 139, 352, 398,  21,  67, 351, 329, 166, 374],
       [321, 375, 357, 386, 383, 260, 224,  49, 439, 329],
       [473, 271, 241, 256, 385, 146,  40,  52, 113, 343],
       [277, 451,  80, 362, 464, 302, 305, 258, 423, 418],
       [ 30, 350,  82, 290, 405, 377, 380, 314, 159, 299],
       [147, 379, 254, 321,  32, 446, 490, 174, 468, 130],
       [248, 199, 403, 172, 421, 359, 450, 462, 461, 160],
       [143, 126, 141, 367, 384,  38, 109,  93, 167,  73],
       [ 47,  49, 222, 259, 443, 153, 471,  21, 187,  69]])

In [128]:
# Q13: Create two 3D NumPy arrays (3x3x3) with random integers
# Perform element-wise addition, multiplication, and matrix multiplication

a1 = nm.random.randint(1, 11, size=(3,3,3))
a2 = nm.random.randint(1, 11, size=(3,3,3))

print("Array 1:\n", a1)
print("\nArray 2:\n", a2)

Array 1:
 [[[ 7 10  7]
  [ 6  1  3]
  [ 1 10  3]]

 [[10  3  4]
  [ 2  2  5]
  [ 9 10  5]]

 [[ 7  8  8]
  [ 6  1  7]
  [ 2  2  6]]]

Array 2:
 [[[ 3  1  3]
  [10  5  8]
  [ 4 10  9]]

 [[ 2  6  5]
  [ 7  7  8]
  [ 8  9  4]]

 [[ 5  8  8]
  [ 2  4  4]
  [10  3  8]]]

In [130]:
print("addition : ",a1+a2)

addition :  [[[10 11 10]
  [16  6 11]
  [ 5 20 12]]

 [[12  9  9]
  [ 9  9 13]
  [17 19  9]]

 [[12 16 16]
  [ 8  5 11]
  [12  5 14]]]

In [131]:
print("multiplication : ",a1*a2)

addition :  [[[ 21  10  21]
  [ 60   5  24]
  [  4 100  27]]

 [[ 20  18  20]
  [ 14  14  40]
  [ 72  90  20]]

 [[ 35  64  64]
  [ 12   4  28]
  [ 20   6  48]]]

In [133]:
print("matrix multiplicatin :", nm.matmul(a1,a2))

matrix multiplicatin : [[[149 127 164]
  [ 40  41  53]
  [115  81 110]]

 [[ 73 117  90]
  [ 58  71  46]
  [128 169 145]]

 [[131 112 152]
  [102  73 108]
  [ 74  42  72]]]

In [136]:
# Q14: Create NumPy arrays using special values:
# - Array of zeros (5x5)
x1=nm.zeros((5,5))
x1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [137]:
# - Array of ones (3x4)
x2=nm.ones((3,4))
x2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [138]:
x3=nm.eye(4)
x3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [140]:
x4 = nm.arange(0, 51, 5)
x4

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [141]:
# Concatenate and stack these arrays

In [143]:
# Q15: Use array slicing to extract:
# - First 3 rows from the Quantity-Price 2D array
arr[:3,:]

array([[    1, 18000],
       [    1, 55000],
       [    2,   800]], dtype=int64)

In [145]:
# - Every alternate element from the Price array
p[::2]

array([18000,   800,  3000, 22000,  1500,  7000,  3500,   600,  1800,
         400,   100,    50,   800], dtype=int64)