In [1]:

import pandas as pd

In [3]:
# 1. Create a Pandas Series using a list of 5 random numbers and custom index names.
#     Then print the series and its data type.
l=[5,4,9,8,7]
d=pd.Series(l,['a','b','c','d','e'])
d

a    5
b    4
c    9
d    8
e    7
dtype: int64

In [15]:
# 2. Create a DataFrame with columns: "Student_Name", "Maths", "Science", "English".
#     Fill it with 5 sample student records and display the top 3 rows using head().
df=pd.DataFrame({
    'name':['ravi','puja','om','ram','raj'],
    'maths':[99,95,74,62,41],
    'science':[75,45,46,41,95],
   'english':[85,76,42,85,65]
})
df

   name  maths  science  english
0  ravi     99       75       85
1  puja     95       45       76
2    om     74       46       42
3   ram     62       41       85
4   raj     41       95       65

In [16]:
df.head(3)

   name  maths  science  english
0  ravi     99       75       85
1  puja     95       45       76
2    om     74       46       42

In [11]:
# 3. Import a CSV file (use any sample dataset) into a DataFrame.
#     Display the number of rows and columns using shape, and print column names.
df2=pd.read_csv("conerted.csv")
df2

  name   age    city  rank  dept    joindate  joinyear
0    a  22.0    pune   1.0    hr  2020-12-31      2020
1    b  23.0     goa   2.0    it  2021-12-31      2021
2    c  34.0  nashik   3.0  sale  2022-12-31      2022
3    d  57.0      up   4.0  prod  2023-12-31      2023

In [12]:
df2.shape

(4, 7)

In [13]:
df2.columns

Index(['name', 'age', 'city', 'rank', 'dept', 'joindate', 'joinyear'], dtype='object')

In [17]:
# 4. Add a new column named "Total_Marks" that sums all three subject scores.
#     Then create another column "Average" by dividing Total_Marks by 3.
df

   name  maths  science  english
0  ravi     99       75       85
1  puja     95       45       76
2    om     74       46       42
3   ram     62       41       85
4   raj     41       95       65

In [18]:
df['total']=df['maths']+df['science']+df['english']
df

   name  maths  science  english  total
0  ravi     99       75       85    259
1  puja     95       45       76    216
2    om     74       46       42    162
3   ram     62       41       85    188
4   raj     41       95       65    201

In [20]:
df['avgrage']=df['total']/3
df

   name  maths  science  english  total    avgrage
0  ravi     99       75       85    259  86.333333
1  puja     95       45       76    216  72.000000
2    om     74       46       42    162  54.000000
3   ram     62       41       85    188  62.666667
4   raj     41       95       65    201  67.000000

In [23]:
# 5. Introduce a missing value (NaN) in the "Science" column and then:
#     (a) Identify missing values using isnull()
df.loc[2,'science']=None
df

   name  maths  science  english  total    avgrage
0  ravi     99     75.0       85    259  86.333333
1  puja     95     45.0       76    216  72.000000
2    om     74      NaN       42    162  54.000000
3   ram     62     41.0       85    188  62.666667
4   raj     41     95.0       65    201  67.000000

In [25]:
df['science'].fillna(df['science'].mean(),inplace=True)
df

C:\Users\91876\AppData\Local\Temp\ipykernel_23776\859092344.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['science'].fillna(df['science'].mean(),inplace=True)

   name  maths  science  english  total    avgrage
0  ravi     99     75.0       85    259  86.333333
1  puja     95     45.0       76    216  72.000000
2    om     74     64.0       42    162  54.000000
3   ram     62     41.0       85    188  62.666667
4   raj     41     95.0       65    201  67.000000

In [28]:
# 6. Filter and display all students whose "Average" score is greater than 75.
df[df['avgrage']>75]

   name  maths  science  english  total    avgrage
0  ravi     99     75.0       85    259  86.333333

In [29]:
# 7. Sort the DataFrame by "Total_Marks" in descending order and show
#the top 3 performers.
df3=df.sort_values(by=['total'],ascending=False)
df3

   name  maths  science  english  total    avgrage
0  ravi     99     75.0       85    259  86.333333
1  puja     95     45.0       76    216  72.000000
4   raj     41     95.0       65    201  67.000000
3   ram     62     41.0       85    188  62.666667
2    om     74     64.0       42    162  54.000000

In [30]:
df.head(3)

   name  maths  science  english  total    avgrage
0  ravi     99     75.0       85    259  86.333333
1  puja     95     45.0       76    216  72.000000
2    om     74     64.0       42    162  54.000000

In [33]:
# 8. Group students based on their "English" score range (like above or below 70)
#     and find the mean of "Maths" and "Science" marks for each group.
df.groupby(df['english']>70)['maths'].mean()

english
False    57.500000
True     85.333333
Name: maths, dtype: float64

In [34]:
df.groupby(df['english']>70)['science'].mean()

english
False    79.500000
True     53.666667
Name: science, dtype: float64

In [39]:
# 9. Merge two DataFrames:
#     (a) One with "Student_Name" and "Total_Marks"
#     (b) Another with "Student_Name" and "Sports_Score"
s1=pd.DataFrame({
    'name':['a','b','c'],
    'total':[99,97,95,]
})
s2=pd.DataFrame({
    'name':['a','b','c'],
    'sport':[87,86,84]
})
s1

  name  total
0    a     99
1    b     97
2    c     95

In [40]:
s2

  name  sport
0    a     87
1    b     86
2    c     84

In [41]:
s1.merge(s2,on='name')

  name  total  sport
0    a     99     87
1    b     97     86
2    c     95     84

In [42]:
# 10. Export the final DataFrame to a CSV file on your Desktop (use os library to define path)
#     and verify if the file is successfully created using os.path.exists().
df.to_csv("demo.csv",index=False)
print("successfully exported")

successfully exported

In [43]:
import os
os.getcwd()

'C:\\Users\\91876\\OneDrive\\Desktop\\inter'